import React, { useState, useEffect } from 'react';
import { Head, router } from '@inertiajs/react';
import { 
    index as adminLearnIndex,
    drafts as adminLearnDrafts,
    store as adminLearnStore,
    destroy as adminLearnDestroy
} from '@/routes/admin/learn';
import {
    Check,
    X,
    Edit3,
    FileText,
    Sparkles
} from 'lucide-react';
import { LessonMarkdown } from '@/components/lesson-markdown';
import { DraftsReviewShell } from '@/components/drafts-review-shell';
import type { CategoryItem } from '@/components/drafts-review-shell';

interface DraftModule {
    id: number;
    title: string;
    slug: string;
    topic: string;
    summary: string;
    content: string;
    estimated_minutes: number;
    category: string;
    subcategory: string;
    approved: boolean;
    isEditing?: boolean;
}

interface DraftsProps {
    initialDrafts?: DraftModule[];
    categories?: CategoryItem[];
}

export default function DraftsLearnList({ initialDrafts = [], categories = [] }: DraftsProps) {
    const [draftModules, setDraftModules] = useState<DraftModule[]>(initialDrafts);
    const [previewMode, setPreviewMode] = useState<Record<number, 'preview' | 'raw'>>({});

    // Sync local state when Inertia refreshes initialDrafts from backend
    useEffect(() => {
        setTimeout(() => {
            setDraftModules(initialDrafts);
        }, 0);
    }, [initialDrafts]);

    // Actions
    const toggleApproveDraft = (id: number) => {
        setDraftModules(prev => prev.map(m => m.id === id ? { ...m, approved: !m.approved } : m));
    };

    const handleToggleAllDrafts = () => {
        const allApproved = draftModules.every(m => m.approved);
        setDraftModules(prev => prev.map(m => ({ ...m, approved: !allApproved })));
    };

    const deleteDraft = async (id: number) => {
        setDraftModules(prev => prev.filter(m => m.id !== id));

        try {
            const csrfToken = (document.querySelector('meta[name="csrf-token"]') as HTMLMetaElement)?.content || '';
            await fetch(adminLearnDestroy(id).url, {
                method: 'DELETE',
                headers: {
                    'X-CSRF-TOKEN': csrfToken,
                    'Accept': 'application/json',
                },
            });
        } catch (err) {
            console.error('Failed to permanently delete draft:', err);
        }
    };

    const toggleEditDraft = (id: number) => {
        setDraftModules(prev => prev.map(m => m.id === id ? { ...m, isEditing: !m.isEditing } : m));
    };

    const handleUpdateDraftField = (id: number, field: keyof DraftModule, val: any) => {
        setDraftModules(prev => prev.map(m => m.id === id ? { ...m, [field]: val } : m));
    };

    const handleCommitApproved = () => {
        const approvedModules = draftModules.filter(m => m.approved);
        if (approvedModules.length === 0) return;

        const modulesToSave = approvedModules.map(m => {
            const { isEditing, approved, ...rest } = m;
            return rest;
        });

        router.post(adminLearnStore().url, {
            modules: modulesToSave,
        }, {
            preserveScroll: true,
        });
    };

    return (
        <>
            <Head title="Learn Drafts Review" />

            <DraftsReviewShell<DraftModule>
                title="Syllabus Drafts Reviewer"
                subtitle="Verify, polish, and publish draft learning modules generated by AI or written manually."
                backUrl={adminLearnIndex().url}
                backLabel="Back to Learn Management"
                items={draftModules}
                categories={categories}
                searchPlaceholder="Search draft titles, syllabus focus topics, subcategories..."
                searchMatcher={(m, search) =>
                    m.title.toLowerCase().includes(search.toLowerCase()) ||
                    m.topic.toLowerCase().includes(search.toLowerCase()) ||
                    m.category.toLowerCase().includes(search.toLowerCase()) ||
                    m.subcategory.toLowerCase().includes(search.toLowerCase())
                }
                commitLabel="Publish Approved"
                onCommit={handleCommitApproved}
                onToggleAll={handleToggleAllDrafts}
                emptyStateTitle="No Syllabus Drafts Pending"
                emptyStateDescription="There are currently no draft modules waiting in the curation pipeline. Launch the AI Lesson Generator or create one manually to populate this review center."
                emptyStateActionUrl="/admin/learn/create"
                emptyStateActionLabel="Generate Syllabus Modules"
                emptyStateActionIcon={Sparkles}
                renderItem={(m) => (
                    <div
                        key={m.id}
                        className={`rounded-2xl border transition duration-205 bg-card p-6 shadow-xs ${m.approved
                            ? 'border-emerald-250 ring-1 ring-emerald-500/10 shadow-emerald-50/10 dark:border-emerald-900/40'
                            : 'border-border hover:border-slate-350 dark:hover:border-slate-700'
                            }`}
                    >
                        {/* Card Header metadata */}
                        <div className="flex items-center justify-between mb-4 border-b border-border pb-3">
                            <div className="flex flex-wrap items-center gap-2">
                                <span className="rounded-full bg-muted border border-border px-3 py-0.5 text-xs font-semibold text-foreground">
                                    {m.category}
                                </span>
                                <span className="rounded-full bg-blue-50 border border-blue-100 px-3 py-0.5 text-xs font-semibold text-blue-700 dark:bg-blue-950/20 dark:border-blue-900/30 dark:text-blue-400">
                                    {m.subcategory}
                                </span>
                                <span className="rounded-full bg-muted border border-border px-3 py-0.5 text-xs font-semibold text-foreground">
                                    ⏱️ {m.estimated_minutes} mins
                                </span>
                                {m.approved ? (
                                    <span className="rounded-full bg-emerald-550/10 border border-emerald-200 px-3 py-0.5 text-xs font-bold text-emerald-700 dark:bg-emerald-950/20 dark:border-emerald-900/30 dark:text-emerald-400">
                                        Approved
                                    </span>
                                ) : (
                                    <span className="rounded-full bg-amber-50 border border-amber-100 px-3 py-0.5 text-xs font-bold text-amber-700 dark:bg-amber-950/20 dark:border-amber-900/30 dark:text-amber-450">
                                        Pending Review
                                    </span>
                                )}
                            </div>

                            {/* Card Actions toolbar */}
                            <div className="flex items-center gap-1.5">
                                <button
                                    type="button"
                                    onClick={() => toggleApproveDraft(m.id)}
                                    className={`p-1.5 rounded-lg border transition cursor-pointer ${m.approved
                                        ? 'bg-emerald-50 border-emerald-200 text-emerald-700 dark:bg-emerald-950/20 dark:border-emerald-900/40 dark:text-emerald-400'
                                        : 'bg-card border-border text-muted-foreground hover:text-foreground'
                                        }`}
                                    title={m.approved ? "Approved (Click to Unapprove)" : "Mark Approved"}
                                >
                                    <Check className="size-4" />
                                </button>
                                <button
                                    type="button"
                                    onClick={() => toggleEditDraft(m.id)}
                                    className={`p-1.5 rounded-lg border transition cursor-pointer ${m.isEditing
                                        ? 'bg-blue-50 border-blue-200 text-blue-700 dark:bg-blue-950/20 dark:border-blue-900/40 dark:text-blue-400'
                                        : 'bg-card border-border text-muted-foreground hover:text-foreground'
                                        }`}
                                    title="Edit Lesson Content Inline"
                                >
                                    <Edit3 className="size-4" />
                                </button>
                                <button
                                    type="button"
                                    onClick={() => deleteDraft(m.id)}
                                    className="p-1.5 rounded-lg border bg-card border-border text-muted-foreground hover:text-red-650 hover:border-red-200 transition cursor-pointer dark:hover:text-red-500"
                                    title="Delete Draft Module"
                                >
                                    <X className="size-4" />
                                </button>
                            </div>
                        </div>

                        {/* Title and Summary Block */}
                        <div className="mb-4 space-y-4">
                            {m.isEditing ? (
                                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                                    <div className="flex flex-col gap-1.5">
                                        <label className="text-xs font-bold text-muted-foreground uppercase">Lesson Title</label>
                                        <input
                                            type="text"
                                            value={m.title}
                                            onChange={(e) => handleUpdateDraftField(m.id, 'title', e.target.value)}
                                            className="w-full rounded-xl border border-border px-3.5 py-2 text-sm font-semibold focus:border-blue-500 focus:outline-none text-foreground bg-background"
                                        />
                                    </div>
                                    <div className="flex flex-col gap-1.5">
                                        <label className="text-xs font-bold text-muted-foreground uppercase">Focus Topic</label>
                                        <input
                                            type="text"
                                            value={m.topic}
                                            onChange={(e) => handleUpdateDraftField(m.id, 'topic', e.target.value)}
                                            className="w-full rounded-xl border border-border px-3.5 py-2 text-sm font-semibold focus:border-blue-500 focus:outline-none text-foreground bg-background"
                                        />
                                    </div>
                                    <div className="flex flex-col gap-1.5 sm:col-span-2">
                                        <label className="text-xs font-bold text-muted-foreground uppercase">Preview Summary</label>
                                        <input
                                            type="text"
                                            value={m.summary}
                                            onChange={(e) => handleUpdateDraftField(m.id, 'summary', e.target.value)}
                                            className="w-full rounded-xl border border-border px-3.5 py-2 text-sm font-semibold focus:border-blue-500 focus:outline-none text-foreground bg-background"
                                        />
                                    </div>
                                    <div className="flex flex-col gap-1.5 sm:col-span-2">
                                        <label className="text-xs font-bold text-muted-foreground uppercase">Markdown Content</label>
                                        <textarea
                                            value={m.content}
                                            onChange={(e) => handleUpdateDraftField(m.id, 'content', e.target.value)}
                                            className="w-full rounded-xl border border-border p-3 text-sm font-semibold focus:border-blue-500 focus:outline-none font-mono text-foreground bg-background"
                                            rows={12}
                                        />
                                    </div>
                                </div>
                            ) : (
                                <div className="space-y-3">
                                    <div>
                                        <h2 className="text-lg font-black text-foreground leading-tight">{m.title}</h2>
                                        <p className="text-xs font-bold text-muted-foreground mt-0.5">Focus: {m.topic}</p>
                                    </div>
                                    <blockquote className="border-l-3 border-border pl-3.5 py-1 text-sm font-semibold text-muted-foreground leading-relaxed bg-muted/40 pr-2 rounded-r-lg">
                                        {m.summary}
                                    </blockquote>

                                    <div className="border border-border rounded-2xl bg-muted/20 p-5 mt-4">
                                        {/* Toggle Mode Tabs */}
                                        <div className="flex items-center justify-between gap-1.5 mb-4 border-b border-border pb-2.5">
                                            <div className="flex items-center gap-1.5">
                                                <FileText className="size-4 text-muted-foreground" />
                                                <span className="text-[10px] font-black tracking-wider uppercase text-muted-foreground">Lesson Material Preview</span>
                                            </div>
                                            
                                            <div className="inline-flex rounded-lg bg-muted p-0.5">
                                                <button
                                                    type="button"
                                                    onClick={() => setPreviewMode(prev => ({ ...prev, [m.id]: 'preview' }))}
                                                    className={`rounded-md px-2 py-1 text-[9.5px] font-extrabold uppercase transition cursor-pointer ${
                                                        (previewMode[m.id] || 'preview') === 'preview'
                                                            ? 'bg-card text-blue-600 shadow-3xs dark:text-white'
                                                            : 'text-muted-foreground hover:text-foreground'
                                                    }`}
                                                >
                                                    Visual Format
                                                </button>
                                                <button
                                                    type="button"
                                                    onClick={() => setPreviewMode(prev => ({ ...prev, [m.id]: 'raw' }))}
                                                    className={`rounded-md px-2 py-1 text-[9.5px] font-extrabold uppercase transition cursor-pointer ${
                                                        previewMode[m.id] === 'raw'
                                                            ? 'bg-card text-blue-600 shadow-3xs dark:text-white'
                                                            : 'text-muted-foreground hover:text-foreground'
                                                    }`}
                                                >
                                                    Raw Source
                                                </button>
                                            </div>
                                        </div>

                                        {(previewMode[m.id] || 'preview') === 'preview' ? (
                                            <div className="text-xs leading-relaxed text-foreground max-h-[450px] overflow-y-auto pr-2">
                                                <LessonMarkdown content={m.content} />
                                            </div>
                                        ) : (
                                            <pre className="text-xs font-mono whitespace-pre-wrap leading-relaxed text-foreground max-h-[300px] overflow-y-auto pr-2 select-all bg-muted p-3 rounded-lg border border-border">
                                                {m.content}
                                            </pre>
                                        )}
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>
                )}
            />
        </>
    );
}

// Register layout configuration
DraftsLearnList.layout = {
    breadcrumbs: [
        {
            title: 'Learn Management',
            href: adminLearnIndex().url,
        },
        {
            title: 'Learn Drafts Review',
            href: adminLearnDrafts().url,
        },
    ],
};
